### ISSUE TITLE
4.9.61

### ISSUE THREAD

**Issue by gitbugged** [minipli/linux-unofficial_grsec#11]
I noticed there was no patch for .60 or .61, I still use these patches regularly.
Hope you are doing well - Keep up the good work! :+1:

**Comment by theLOICofFRANCE** [comment]
He must be busy. Here is for version 4.9.61:
http://dl.free.fr/wYcIreCYr

**Comment by theLOICofFRANCE** [comment]
Minipli [commented on 14 Jul: "I was on vacation and had no time to do the porting. Sorry..."](https://github.com/minipli/linux-unofficial_grsec/issues/5#issuecomment-315336472)

It must be similar here. As you mentioned, he's a good worker ;)
That's why I'm here and that's why it has recovered a lot of loyal grsecurity users.

Let's let him rest and hope he's well.

**Comment by miroR** [comment]
On 171111-12:50+0000, Loïc wrote:
> Minipli [commented on 14 Jul: "I was on vacation and had no time to do the porting. Sorry..."](https://github.com/minipli/linux-unofficial_grsec/issues/5#issuecomment-315336472)
> 
> It must be similar here. As you mentioned, he's a good worker ;)
> That's why I'm here and that's why it has recovered a lot of loyal grsecurity users.
> 
> Let's let him rest and hope he's well. 

Please, HacKurx (or Loïc if that name I should use --at https://github.com/minipli/linux-unofficial_grsec/issues/11 it's HacKurx for the text above, while in my mailbox it's Loïc--), can you pls. give that download at: http://dl.free.fr/wYcIreCYr an PGP-signature?

The same that you use, if you do, on Github?

( No, you don't... I looked up https://github.com/slimm609/checksec.sh/releases, you don't sign you releases, or am I missing something?, very possible, don't get me wrong --and I didnt' check if you sign commits maybe--, I'm not very advanced. )

Or if you can't sign it, pls. can you confirm that your file identifies with this SHA256 hash:

3af330c2a71198daa3f60a710b4b5bfd5d80b4c800f1fa94738a047527fc6b06  v4.9.61-unofficial_grsec-HacKurx.diff.tar.xz

I'm having Call Traces now (actually they stopped a while ago...) with the 4.9.59... I crave for free unofficial-grsec updated against possible new exploits that grow fast always... And I will give it a try, but I do need verifiable, non-repudiatable sources. I trust Mr. PGP...

And I hope minipli is back soon. There are people here who miss your work... I sure hope, and wish, that you are well, minipli, and that nothing happened to you.

Thank you!

-- 
Miroslav Rovis
Zagreb, Croatia
https://www.CroatiaFidelis.hr

**Comment by theLOICofFRANCE** [comment]
@miroR Hi !
Yes, Loic is my first name and it's easier to pronounce ;)

I mainly use github to communicate openly with developers. I'm not a big fan of this platform which has a monopoly and yet is not able to have an interface in the language...

Yes, I will be able to use [PGP](https://github.com/roundcube/roundcubemail/issues/5645) ^^

sha256sum of v4.9.61-unofficial_grsec-HacKurx.diff : **ee194f81c793f1f3cfc9ab980e0135eca4abf57db9d214306ab8f2838a7b7096**

**Comment by miroR** [comment]
On 171114-19:19+0000, Loïc wrote:
> @miroR Hi !
> Yes, Loic is my first name and it's easier to pronounce ;)
> 
> I mainly use github to communicate openly with developers. I'm not a big fan of this platform which has a monopoly and yet is not able to have an interface in the language...
> 
> Yes, I will be able to use [PGP](https://github.com/roundcube/roundcubemail/issues/5645) ^^
I share your attitude about github... But we will be needing it... And I hope it don't become as bad as, say Google... So far, they appear to me much more honest... But, hard to tell...

Anyway, for Github, if you want to get your work signed, you need to upload your PGP-key to Github... Wrong, because there are good round-robin SKS servers round the world, and up until a year or two ago, Github simply used those, like anybody/any entity does, but all of a sudden they started requiring users to upload their PGP-keys... So that is monopolistic, you are right...

But anyway, for Github, if you want to get your work signed, look up their help and upload your PGP-key.

> sha256sum: **ee194f81c793f1f3cfc9ab980e0135eca4abf57db9d214306ab8f2838a7b7096** 
> 
Sure! That's it. Thanks!

Thanks! I'll see if I can compile 4.9.61 with your patch this evening and report how my system fares as soon as I can. (Not too well this eveing, so can't promise.)

-- 
Miroslav Rovis
Zagreb, Croatia
https://www.CroatiaFidelis.hr

**Comment by miroR** [comment]
On 171114-20:34+0000, Miroslav Rovis wrote:
> On 171114-19:19+0000, Loïc wrote:
[...]
> > sha256sum: **ee194f81c793f1f3cfc9ab980e0135eca4abf57db9d214306ab8f2838a7b7096** 
[...]
> 
> Thanks! I'll see if I can compile 4.9.61 with your patch this evening and report how my system fares as soon as I can. (Not too well this eveing, so can't promise.)

I just compiled it (in my Air-Gapped master machine, the cleanest that it gets, well, up to my level of scarce expertize only), and I'm running it as I write in this for-online clone machine:

$ uname -r
4.9.61-unofficial+grsec171114-20
$

In case you don't soon hear from me, and shouting at you :-)  (no, I'll be nice whichever the case will be, there's no guarrantie in FOSS), it is running quietly and obediently :-). It booted just fine, feels nice so far...

In which case I might (but read on for another, possibly better, option) try and put the 1.5MB of it's worth at:
https://www.CroatiaFidelis.hr/gnu/deb/
so people might have a second location where to get it, and if you don't make it verifiable (probably best do it just like minipli does), I'll sign it with my PGP-key, only because of verifiability, with big fat notice that you are the author of it, not me.

But the other option is you try and make it a pull request?... Just thinking.

On another note, I have Xorg running as root because I have now old AMD ATI Radeon cards in my machines... It's urgent for me to get gradm deployed... Long overdue urgent...

See this page about Gradm:

https://www.CroatiaFidelis.hr/gnu/gradm/

Is there any other work somewhere else on Gradm unofficial, anybody?

-- 
Miroslav Rovis
Zagreb, Croatia
https://www.CroatiaFidelis.hr

**Comment by miroR** [comment]
I uploaded:
https://www.croatiafidelis.hr/gnu/deb/linux-deb-4.9.61-unofficial+grsec171114-19/

and posted about it at:
https://dev1galaxy.org/viewtopic.php?id=1598#p5133
and:
http://forums.debian.net/viewtopic.php?f=16&t=108616&p=658753#p658753

Regards!

**Comment by theLOICofFRANCE** [comment]
For the version 4.9.62 the commits 7c4788950ba5922fde976d80b72baf46f14dee8d and [cef572a](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cef572ad9bd7f85035ba8272e5352040e8be0152) its has to be examined.

> Is there any other work somewhere else on Gradm unofficial, anybody?

Gradm is still maintained by Brad and freely accessible. Latest release: [gradm-3.1-201709030627.tar.gz](https://grsecurity.net/stable/gradm-3.1-201709030627.tar.gz) and to [follow its development](https://cvsweb.grsecurity.net/?p=gradm.git;a=summary).

Thanks.

**Comment by theLOICofFRANCE** [comment]
Pending the return of Mathias, please find my version of the patch for kernel 4.9.62:
http://dl.free.fr/nWLA9omeg

sha256sum of v4.9.62-unofficial_grsec-HacKurx.diff : 
**c2eb0bdf1ad32a1e6290f2bb106f79dad1c7e7f77d07b79353a416bbeb583716**

Best regards,

**Comment by miroR** [comment]
Loic, (HacKurx), your patch behaves fine, to my best understanding! I recommend it to visitors!
[removed some temporary notices to Loic from here]

**Comment by miroR** [comment]
No, I'm sorry, it could be MiTM or some other nuissance...
[ previously here was notice about which temporary and later removed file address from http://dl.free.fr/ was not downloading ]
but it does not download for me...
Can other visitors download it, if anybody can confirm?
UPDATE: no it wasn't MiTM, and nobody could download it, it was githutweets being incompatible with what you get in your mailbox.

**Comment by miroR** [comment]
[removed some temporary notices to Loic from here]
Maybe go more slowly (maybe even think about forking the repo, since you can program in C, I can't well at all...), upload your PGP-key and follow how minipli was doing, to keep with the tradition... Just thinking.
Again: Can other visitors download it (the link that remains, with the "nWLA9omeg" string to the file), if anybody can confirm?

**Comment by miroR** [comment]
[removed some temporary notices to Loic from here]
Guys and gals, we desperately need an unofficial_grsecurity (or maybe take the corsac's suggested name grsecunoff [1] or slightly modified grsec-unoff), dedicated mailing list or a dedicated forum. Desperately!
[1] as per https://packages.debian.org/sid/linux-image-4.9.0-4-grsec-amd64, where it reads in the title:
Package: linux-image-4.9.0-4-grsec-amd64 (4.9.51-1+grsecunoff2) cosac is the nickname of Yves-Alexis Perez who has recently brought grsec-unoff back into full-blooded life with packaging it for the largest world GNU/Linux distro, the Debian.
The historic moment timestamped in early October 2017:
https://packages.qa.debian.org/l/linux-grsec/news/20171004T100038Z.html

**Comment by theLOICofFRANCE** [comment]
> Again: Can other visitors download it

Otherwise it's available [here](https://github.com/HacKurx/public-sharing).

> and follow how minipli was doing, to keep with the tradition...

My goal is not to compete, just help you ... Mathias must be on vacation or busy. Be patient ^^

**Comment by miroR** [comment]
Thanks for helping out! Yes, patience is a good and needed friend.
Posting a Call Trace with yout 4.9.61 patch over at:
https://github.com/minipli/linux-unofficial_grsec/issues/13
( till then just the link to:
https://www.croatiafidelis.hr/foss/cap/cap-171117-grsec-RAP-Oops/index.php 
is there; unless another Oops break my routine unexpectedly)

**Comment by sempervictus** [comment]
My fork has 4.9.63 if anyone's interested, along with SCST fixes to run with CONSTIFY plugin in a separate branch (what a PITA to figure that one out, its not just pax_open()/close(), they externed a struct taking sysfs opts). Hopefully i didn't blow anything up too much with the merge fixes made over the last couple of revisions.

**Comment by miroR** [comment]
> My fork has 4.9.63

@sempervictus It must be this one:

https://github.com/sempervictus/linux-unofficial_grsec/tree/4.9.x-even_more_unofficial_grsec

https://github.com/sempervictus/linux-unofficial_grsec/commit/36cf057a7e29d86f5d9982c59a4d1885ed151e74

I'll see if I can figure out and test it (no promise; and also I can only test, not program in C at this time).

**Comment by miroR** [comment]
> My fork has 4.9.63 if anyone's interested, along with SCST fixes to run with CONSTIFY plugin in a separate branch

@sempervictus I can't get just your patch for 4.9.63
E.g. I try:
[this](https://github.com/minipli/linux-unofficial_grsec/compare/master...sempervictus:linux-4.9.x-unofficial_grsec)
but it says

> x  Can’t automatically merge. Don’t worry, you can still create the pull request.

( and I got HacKurx 4.9.63 patch with partial reverse running fine --so far-- as I'm writing this. )

**Comment by miroR** [comment]
[This](https://github.com/sempervictus/linux-unofficial_grsec/compare/v4.9.63...v4.9.63-unofficial_grsec.diff) says:

> There isn’t anything to compare.

while back in early days with minipli, I would get a patch that way:
[gentoo ML archives](https://lists.gt.net/gentoo/hardened/326262#326262)

where find:
```
$ curl https://github.com/minipli/linux-unofficial_grsec/compare/v4.9.27...v4.9.27-unofficial_grsec.diff
> ~/unofficial_grsec-v4.9.27.diff 
```

**Comment by miroR** [comment]
@HacKurx, thanks for telling me.
>  Gradm is still maintained by Brad and freely accessible. Latest release: gradm-3.1-201709030627.tar.gz and to [follow its development](https://cvsweb.grsecurity.net/?p=gradm.git;a=summary).

I'm trying to figure out how to verify gradm releases. If anybody can tell how to do that, thanks!

**Comment by minipli** [comment]
As @HacKurx already guessed, I was on a holiday trip. But ports for v4.9.60 up to v4.9.64 are available now, tagged and pushed (see [releases](https://github.com/minipli/linux-unofficial_grsec/releases)).

Thanks folks, for filling the gap in the meantime!

**Comment by theLOICofFRANCE** [comment]
@minipli Thank you for coming back ;)
